version: '3.9'

services:
  db:
    container_name: mysql8
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_login
      MYSQL_USER: login
      MYSQL_PASSWORD: login
    ports:
      - "3306:3306"
    volumes:
      - db_login:/var/lib/mysql
    networks:
      - login

volumes:
  db_login:

networks:
  login:
    driver: bridge
